name: dart_fundamentos
description: projeto referente ao curso de dart fundamento da academia do flutter
version: 1.0.0
repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <3.3.4'


dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
